### ISSUE TITLE
Daily overview too small edit next to impossible on 4k screens (tested with 3840 x 2400)

### ISSUE THREAD

**Issue by mlrdev** [fochlac/Tempo-Tracker#2]
When using the plugin on a 4k / 3840 x 2400 display on Windows, 100% scale in Edge 101.0121053,
the timeline shrinks to a couple of pixels, which makes it next to impossible to edit entries or navigate through them.

![image](https://user-images.githubusercontent.com/8323838/170960545-efe8650c-2349-4e24-afc5-7c3d98545503.png)

**Comment by fochlac** [comment]
I think I found a solution, 2.0.2 should fix this
