### ISSUE TITLE
Work description

### ISSUE THREAD

**Issue by prog76** [fochlac/Tempo-Tracker#5]
is it possible to add work description when we save the work log entry?

**Comment by fochlac** [comment]
There is currently no way to add a description, as we do not use it in our organisation. However, it should be quite easy to add an input for this, so I'll have a look.

**Comment by fochlac** [comment]
I added some functionality for handling comments. Per default only via an additional button on existing worklogs, however I added a switch in the options to also show them in the worklog list and add a comment directly while tracking.

![image](https://user-images.githubusercontent.com/19147668/219941559-46b8a2bc-0c62-444e-a93f-c2b0f61bc886.png)
![image](https://user-images.githubusercontent.com/19147668/219942056-48a6aeae-0cfd-4558-91de-e1ce4381abcd.png)
![image](https://user-images.githubusercontent.com/19147668/219942096-57609b3f-f09b-4560-9794-d28636f57727.png)
