### ISSUE TITLE
Unable to find the JIRA-Api

### ISSUE THREAD

**Issue by zabojpetr** [fochlac/Tempo-Tracker#7]
Hello,

after upgrade Jira in our company, I am not able to connect to jira with this addon. Tracker shows: Unable to find the JIRA-Api with the provided Domain.
![obrazek](https://github.com/fochlac/Tempo-Tracker/assets/6089349/e42b6dda-819e-4d47-a261-5d1510d6450b)

But when I try the rest api, it works well.
![obrazek](https://github.com/fochlac/Tempo-Tracker/assets/6089349/373611ef-802e-4d44-a1bb-d57275cc89b7)

Is there something I can do to addon start working?

**Comment by fochlac** [comment]
Hi, the plugin uses for the api-validation the regexp `/(https?:\/\/|^)(([\w-]+\.|)[\w-]+\.\w+)(\/|$)/` and the endpoint `/rest/api/2/myself`.
You can check if your url matches the regexp, if not I can adapt it if you give me a sample of the url. If it does match the url you can switch to the popout version of the plugin:
![image](https://github.com/fochlac/Tempo-Tracker/assets/19147668/9effcc4e-2658-4443-9b0b-100af536781e)
and can open the devtools and to check if the request fails.
![image](https://github.com/fochlac/Tempo-Tracker/assets/19147668/59d9c1fc-89d8-4a1c-9a4c-426a7ba1e828)

**Comment by zabojpetr** [comment]
Hi, thanks for your answer. You are right, the problem is with the regex. The domain looks like `https://sub11.sub1.dom.tld` so the regex could looks like this to work: `(https?:\/\/|^)(([\w-]+\.)*[\w-]+\.\w+)(\/|$)` for 0-unlimited number of subdomains?

**Comment by fochlac** [comment]
I added a fix and published a patch version. I think the new version should be published within an hour or so. :)

**Comment by zabojpetr** [comment]
Thank you, now it works again! 👍
